### ISSUE TITLE
script error

### ISSUE THREAD

**Issue by Motophan** [excludedBittern8/ahdcross_seed#1]
File "ahd_cross.py", line 1097
    return
SyntaxError: 'return' outside function

which fd
/usr/bin/fd
gentoo@10925199:~/ahdcross_seed$ pip install requests guessit docopt xmltodict IMDbPY
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: requests in /home/gentoo/.local/lib/python3.7/site-packages (2.24.0)
Requirement already satisfied: guessit in /home/gentoo/.local/lib/python3.7/site-packages (3.1.0)
Requirement already satisfied: docopt in /home/gentoo/.local/lib/python3.7/site-packages (0.6.2)
Requirement already satisfied: xmltodict in /home/gentoo/.local/lib/python3.7/site-packages (0.12.0)
Requirement already satisfied: IMDbPY in /home/gentoo/.local/lib/python3.7/site-packages (2020.9.25)
Requirement already satisfied: certifi>=2017.4.17 in /home/gentoo/.local/lib/python3.7/site-packages (from requests) (2017.4.17)
Requirement already satisfied: chardet<4,>=3.0.2 in /home/gentoo/.local/lib/python3.7/site-packages (from requests) (3.0.3)
Requirement already satisfied: idna<3,>=2.5 in /home/gentoo/.local/lib/python3.7/site-packages (from requests) (2.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /home/gentoo/.local/lib/python3.7/site-packages (from requests) (1.25.11)
Requirement already satisfied: rebulk==2.* in /home/gentoo/.local/lib/python3.7/site-packages (from guessit) (2.0.0)
Requirement already satisfied: six in /home/gentoo/.local/lib/python3.7/site-packages (from guessit) (1.13.0)
Requirement already satisfied: babelfish in /home/gentoo/.local/lib/python3.7/site-packages (from guessit) (0.5.5)
Requirement already satisfied: python-dateutil in /home/gentoo/.local/lib/python3.7/site-packages (from guessit) (2.6.1)
Requirement already satisfied: lxml in /home/gentoo/.local/lib/python3.7/site-packages (from IMDbPY) (4.6.1)
Requirement already satisfied: SQLAlchemy in /home/gentoo/.local/lib/python3.7/site-packages (from IMDbPY) (1.3.11)

`python ahd_cross.py --fd /usr/bin/fd --torrent /home/gentoo/torrents/ --txt /home/gentoo/torrents/ahd.txt --mvr /home/gentoo/torrents/qbittorrent/ --tvr /home/gentoo/torrents/qbittorrent/ --api redacted--cookie /home/gentoo/cookies.txt`

**Comment by Motophan** [comment]
Commenting the line 

Traceback (most recent call last):
  File "ahd_cross.py", line 53, in <module>
    import pathlib
ImportError: No module named pathlib


pip install pathlib

Defaulting to user installation because normal site-packages is not writeable
Collecting pathlib
  Downloading pathlib-1.0.1.tar.gz (49 kB)
     |████████████████████████████████| 49 kB 701 kB/s
Building wheels for collected packages: pathlib
  Building wheel for pathlib (setup.py) ... done
  Created wheel for pathlib: filename=pathlib-1.0.1-py3-none-any.whl size=14347 sha256=f2e8a04c693280a8d1e09f8985b1fb93009b7608216c2f20cf340a8b1a17bb90
  Stored in directory: /home/gentoo/.cache/pip/wheels/6e/96/b8/10037fe231e23970bac58361d7c93571ab983a7bbc55e68550
Successfully built pathlib
Installing collected packages: pathlib
Successfully installed pathlib-1.0.1

Traceback (most recent call last):
  File "ahd_cross.py", line 53, in <module>
    import pathlib
ImportError: No module named pathlib

**Comment by datawhores** [comment]
I apologize I think you might have been using an old version of the script from now on I will be making a dev channel of this script for testing out any changes. Since sometimes things aren't as stable as I beleive. 

Please update
