### ISSUE TITLE
Documentation improvement

### ISSUE THREAD

**Issue by Motophan** [excludedBittern8/ahdcross_seed#2]
I cannot figure out how to use the tool. I dont know if there is a error with the tool or if the documentation can be cleaned up.

If I wanted to cross seed all the stuff I have in /home/gentoo/torrents/qbittorrent/ 

I assume I would run `python3 ahd_cross.py scan --txt /home/gentoo/torrents/ahd.txt --fd /usr/bin/fd --torrent /home/gentoo/torrents/ahdwatch --mvr /home/gentoo/torrents/qbittorrent/ --tvr /home/gentoo/torrents/qbittorrent/ --api apicodegoeshere --cookie /home/gentoo/cookies.txt --exclude /****/games,/****/music`

What I am trying to do

1- exclude these directories
/home/gentoo/torrents/games -> games, nothing cross seed-able on AHD
/home/gentoo/torrents/music -> music, nothing cross seed-able on AHD

2- make a text file so the known files do not get scanned again and hit the api too much

3- download the .torrent files and put them into /home/gentoo/ahdwatch for me to use autotorrent/dump them into a watch folder to add them to my client

4- somehow tell me what can (likely) be uploaded to ahd

**Comment by Motophan** [comment]
If I completly fill out example.config and I run `python3 ahd_cross.py grab --config example.config` it will just run and finish, I think this is related to https://github.com/excludedBittern8/ahdcross_seed/issues/1 since I had to comment out the return line

**Comment by datawhores** [comment]
On one end I can't cover every possible issue a user could have in the documentation. However I do agree that they are sparse in some areas. Which may lead to some confusion

Where you able to get it working?

**Comment by datawhores** [comment]
Their some new documentation
I think that will fix this issue
